//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quadra_Technology.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public System.Guid StaffId { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string StaffName { get; set; }
        public string StaffLastName { get; set; }
        public Nullable<System.DateTime> StaffbirthDate { get; set; }
        public string StaffAddress { get; set; }
        public string StaffTel { get; set; }
        public string StaffEmail { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> Begin_Working_day { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
    }
}
